// lib/fallback-data.ts — SAHIL PANCHAL real portfolio data
import type { Profile, Project, Skill, Experience, Certification, Education } from "@/types";

export const fallbackProfile: Profile = {
  id: "1",
  name: "Sahil Panchal",
  title: "Software Engineer | Full-Stack & AI 🤖",
  tagline: "Building scalable software, AI-powered applications, and secure backend systems with clean architecture, modern technologies, and real-world impact.",
  location: "Ahmedabad, Gujarat, India · Open to Remote & Relocate",
  email: "sahilpanchal1818@gmail.com",
  phone: "+91 95586 47711",
  linkedin: "https://linkedin.com/in/sahilpanchal2004/",
  github: "https://github.com/S1A8H3I4L",
  portfolio_url: "https://sahil-panchal.vercel.app/",
  resume_url: "/Sahil_Resume.pdf",
  years_learning: 3,
  projects_count: 16,
  certificates_count: 5,
  bio: "I'm a Software Engineer passionate about designing and developing scalable web applications, intelligent AI-powered systems, and user-centric digital products. I enjoy transforming complex ideas into reliable, high-performance solutions that combine clean architecture with exceptional user experience. My experience spans full-stack development, backend engineering, AI/ML integration, authentication systems, payment workflows, REST APIs, and modern responsive interfaces. Through self-driven projects, I've built complete production-style applications — from secure authentication and admin dashboards to AI-based solutions and automation tools. I continuously explore new technologies, strengthen my problem-solving skills, and focus on writing clean, maintainable, and scalable code. My goal is to contribute to engineering teams that build innovative products used by millions while continuously learning and growing as a software engineer.",
  currently_learning: ["LangChain", "Next.js 14", "Docker", "Kubernetes", "Vector Databases", "System Design", "Open Source Contribution"],
};

export const fallbackProjects: Project[] = [
  // ── JULY 2026 ──
  {
    id: "1", slug: "shiftwork-hrms", order: 1, accent: "yellow", featured: true,
    cover_emoji: "🏢", role: "Solo Full Stack Developer", duration: "Odoo Hackathon · Jul 2026",
    name: "Shiftwork – HRMS",
    subtitle: "Human Resource Management System | Odoo Hackathon",
    description: "A full-stack HRMS using React, Node.js, Express.js, and SQLite to manage employees, attendance, leave, and payroll with role-based dashboards.",
    long_description: "Shiftwork is a complete Human Resource Management System built during the Odoo Hackathon. It handles the full employee lifecycle — from onboarding with auto-generated login IDs, to daily attendance check-in/out, time-off requests with a multi-level approval workflow, and salary structure management. The system enforces strict role-based access control where Admin, HR, and Employee roles each see a tailored dashboard. The Neo-Brutalist UI uses a bone-paper background with electric indigo as the accent, and every status badge is styled as a slightly rotated ink stamp — a nod to the physical time-card this system replaces.",
    features: [
      "JWT + bcrypt auth with auto-generated employee login IDs (e.g. OIJODO20260001)",
      "Role-based dashboards: Admin / HR / Employee with protected routes",
      "Attendance check-in/out with live green/red LED in the navbar",
      "Leave request & approval workflow with balance tracking",
      "Salary structure management with auto-calculated components",
    ],
    challenges: [
      "Generating deterministic, collision-free login IDs from company initials + name + year + serial",
      "Keeping attendance, leave balances, and payroll in sync without a heavy ORM",
      "Designing a Neo-Brutalist UI that feels professional, not gimmicky",
    ],
    tech_stack: ["React", "Node.js", "Express.js", "SQLite", "JWT", "bcrypt"],
    // live_url: "#", 
    github_url: "https://github.com/S1A8H3I4L/Human-Resource-Management-System",
  },
  // ── JUNE 2026 ──
  {
    id: "2", slug: "neon-snake-arena", order: 2, accent: "teal", featured: true,
    cover_emoji: "🐍", role: "Solo Developer", duration: "Self Learning · Jun 2026",
    name: "Neon Snake Arena",
    subtitle: "Full-Stack Browser Snake Game | Django",
    description: "A browser-based Snake game with persistent player profiles, a dynamic leaderboard, and a custom Django Admin analytics dashboard — built with Django, HTML5 Canvas, and SQLite.",
    long_description: "Neon Snake Arena is the web rewrite of a Pygame desktop Snake game. Players enter their name, play in the browser via HTML5 Canvas, and every score is saved to a database. The leaderboard ranks each player by their personal best (not every run), and a custom Django Admin dashboard shows aggregate stats — Total Players, Total Games Played, Top Score Ever, Average Score, Best Player, Most Active Player, and Top 5 Rankings. Session-based player tracking and CSRF-protected score submission keep the competitive integrity intact.",
    features: [
      "HTML5 Canvas Snake with collision detection, pause, and dynamic speed ramp-up",
      "Persistent player profiles — same name accumulates score history",
      "Leaderboard ranked by personal best score",
      "Custom Django Admin analytics dashboard with aggregate stats",
      "15 automated tests covering name validation, sessions, score persistence, and leaderboard ranking",
    ],
    challenges: [
      "Trusting the Django session (not a client-supplied ID) for score submission to prevent spoofing",
      "Keeping CSRF protection on for the AJAX score-save call without disabling it",
      "Balancing per-game history storage with a clean leaderboard that shows only best scores",
    ],
    tech_stack: ["Django", "Python", "JavaScript", "HTML5 Canvas", "SQLite", "CSS3"],
    // live_url: "#", 
    github_url: "https://github.com/S1A8H3I4L/Neon-Snake-Arena",
  },
  // ── MARCH 2026 (Pursuing) ──
  {
    id: "3", slug: "chronosend", order: 3, accent: "pink", featured: true,
    cover_emoji: "⏳", role: "Solo Developer", duration: "Self Learning · Mar 2026 – Present",
    name: "ChronoSend",
    subtitle: "Message Scheduling & Automation Platform",
    description: "A full-stack message scheduling platform supporting multi-channel delivery (Email & SMS) with precise time-based automation, Firebase real-time sync, and a rich text editor.",
    long_description: "ChronoSend — from Chronos (time) + Send (delivery) — is built to automate digital communication with precision. Users authenticate via Google Sign-In, compose messages with a rich text editor, add multiple recipients, and schedule delivery for a future time via Email or SMS. Messages are stored in Firestore and dispatched by a Node.js + node-cron background service. A real-time dashboard using Firestore onSnapshot listeners shows live queue status (Pending / Sent / Failed) without any manual refresh.",
    features: [
      "Multi-channel delivery: Email (Nodemailer) and SMS",
      "Google OAuth via Firebase Authentication",
      "Real-time dashboard with Firestore onSnapshot listeners",
      "Rich text editor (ReactQuill) for message composition",
      "node-cron background scheduler for precise timed delivery",
    ],
    challenges: [
      "Ensuring sub-second cron accuracy for scheduled message dispatch",
      "Handling Firestore security rules to isolate each user's message queue",
      "Rich text serialisation for multi-channel output (email HTML vs. SMS plain text)",
    ],
    tech_stack: ["React", "Python", "TypeScript", "Node.js", "Express", "Firebase", "Firestore", "Tailwind CSS", "node-cron"],
    // live_url: "#", 
    // github_url: "https://github.com/S1A8H3I4L",
  },
  // ── MARCH 2026 ──
  {
    id: "4", slug: "secureauth-dashboard", order: 4, accent: "blue", featured: false,
    cover_emoji: "🔐", role: "Solo Developer", duration: "Self Learning · Mar 2026",
    name: "SecureAuth Dashboard",
    subtitle: "Authentication & Real-Time Analytics Platform",
    description: "A production-ready authentication system with Google OAuth, real-time Firestore analytics dashboard, role-based access control, and an admin user-management panel.",
    long_description: "SecureAuth Dashboard is a full authentication + analytics platform demonstrating production-grade security practices. It features Google OAuth via Firebase, session handling, protected routes, and a role-based admin panel. The analytics dashboard pulls live data from Firestore and renders interactive charts (Recharts) with zero manual refresh — all driven by onSnapshot listeners. Security decisions include environment-based configuration, strict Firestore rules, and Firebase API key domain restrictions.",
    features: [
      "Google OAuth + email/password login with session handling",
      "Real-time analytics dashboard with Recharts and Firestore listeners",
      "Role-based access control with admin user management panel",
      "Protected routes with clean error boundaries and failure states",
      "Firestore security rules + domain-restricted API keys",
    ],
    challenges: [
      "Designing Firestore rules that are strict yet don't block legitimate admin reads",
      "Keeping chart data fresh without hammering Firestore with polling",
      "Making RBAC feel seamless without a dedicated backend role service",
    ],
    tech_stack: ["React", "TypeScript", "Vite", "Firebase", "Firestore", "Tailwind CSS", "Recharts", "Motion"],
    live_url: "https://secure-auth-dashboard.vercel.app/", 
    github_url: "https://github.com/S1A8H3I4L/Secure-Auth-Dashboard",
  },
  // ── MARCH 2026 (Hackathon) ──
  {
    id: "5", slug: "reimbursement-management", order: 5, accent: "yellow", featured: false,
    cover_emoji: "💼", role: "Solo Full Stack Developer", duration: "Odoo Hackathon · Mar 2026",
    name: "Reimbursement Management System",
    subtitle: "Smart Expense Reimbursement | Odoo Hackathon",
    description: "A smart, automated reimbursement system with multi-level approval workflows, OCR receipt scanning, conditional approval rules, and multi-currency support.",
    long_description: "Built for the Odoo Hackathon, this system eliminates manual, error-prone expense reimbursement. Employees submit claims with OCR-extracted receipt data. The approval flow is fully configurable: sequential (Manager → Finance → Director), percentage-based (60% approve → approved), or CFO-bypass rules. Real-time Firestore listeners update every dashboard instantly. Multi-currency support with live exchange rates via restcountries.com and exchangerate-api.com means no manual conversion.",
    features: [
      "OCR receipt scanning: auto-extracts Amount, Date, Description, Merchant",
      "Multi-level approval: sequential, percentage-based, and CFO-bypass rules",
      "Multi-currency with live exchange rate conversion",
      "Real-time status updates via Firestore onSnapshot",
      "Role-based dashboards: Employee / Manager / Admin",
    ],
    challenges: [
      "Implementing conditional approval logic (percentage vs. specific approver vs. hybrid) in a clean, configurable way",
      "OCR field extraction accuracy for handwritten or low-quality receipts",
      "Currency conversion on submission vs. conversion at approval time",
    ],
    tech_stack: ["React", "Vite", "Node.js", "Express", "Firebase", "Firestore", "Tailwind CSS", "OCR API"],
    // live_url: "#",
    github_url: "https://github.com/S1A8H3I4L/Reimbursement-Management",
  },
  // ── MAR 2026 ──
  {
    id: "6", slug: "skillswap", order: 6, accent: "teal", featured: false,
    cover_emoji: "🔄", role: "Solo Developer", duration: "Self Learning · Mar 2026",
    name: "SkillSwap",
    subtitle: "Skill Exchange & Collaborative Learning Platform",
    description: "A community-driven platform connecting learners and mentors for skill exchange, with real-time swap requests, built-in chat, and personalized profiles.",
    long_description: "SkillSwap is the Airbnb of skills — you list what you know and what you want to learn, then find someone to swap with. The platform uses React + TypeScript on the frontend with an Express + SQLite backend. Users can filter the community by skill category, send a swap proposal with a personalized message, and manage incoming/outgoing requests from a real-time dashboard. The glassmorphism UI with smooth Motion animations makes the exchange feel premium.",
    features: [
      "Skill discovery with category filters (Technology, Arts, Languages, etc.)",
      "Modal-based swap request system with personalized proposals",
      "Real-time dashboard for managing incoming and outgoing requests",
      "Full auth flow: login, registration, and protected profile pages",
      "Express + SQLite backend with Better-SQLite3 for high-performance reads",
    ],
    challenges: [
      "Matching users bidirectionally (A wants B's skill AND B wants A's skill) without complex queries",
      "Keeping the swap request state consistent between the requester and receiver dashboards",
      "Designing a glassmorphism UI that loads fast without heavy CSS overhead",
    ],
    tech_stack: ["React", "TypeScript", "Tailwind CSS", "Express.js", "SQLite", "Motion", "Lucide React"],
    // live_url: "#", 
    // github_url: "https://github.com/S1A8H3I4L",
  },
  // ── FEB 2026 ──
  {
    id: "7", slug: "rewear", order: 7, accent: "pink", featured: false,
    cover_emoji: "♻️", role: "Solo Developer", duration: "Self Learning · Feb 2026",
    name: "ReWear",
    subtitle: "Sustainable Community Clothing Exchange",
    description: "A modern web platform reducing textile waste through community-driven clothing exchange with a points-based system, category browsing, and transparent swap tracking.",
    long_description: "ReWear addresses the fashion industry's waste problem by enabling peer-to-peer clothing exchange through a smart points economy. Users list garments, browse by category, propose swaps, and track their environmental impact. The 'Sage & Clay' colour palette (Sage #4A5D4E for growth, Clay #F7F3F0 for warmth) reinforces the sustainability ethos. An admin moderation layer with an automatic penalty system keeps the community fair and transparent.",
    features: [
      "Points-based clothing exchange with negative balance recovery",
      "Category browsing: Men, Women, Kids, Accessories",
      "Admin moderation with automatic penalty and user restriction controls",
      "Smart dashboard: track listings, swaps, and points earned",
      "Glassmorphism UI with 'Sage & Clay' sustainability colour palette",
    ],
    challenges: [
      "Designing a points economy that prevents gaming/hoarding while staying fair",
      "Building a moderation system that scales without requiring constant admin attention",
      "Persisting swap state across sessions using localStorage without a backend",
    ],
    tech_stack: ["React", "TypeScript", "Tailwind CSS", "React Router", "Lucide React", "LocalStorage"],
    // live_url: "#", 
    github_url: "https://github.com/S1A8H3I4L/ReWear",
  },
  // ── JAN 2026 – PURSUING ──
  {
    id: "8", slug: "schoolguard", order: 8, accent: "blue", featured: false,
    cover_emoji: "🛡️", role: "Solo Developer", duration: "Self Learning · Jan 2026 – Present",
    name: "SchoolGuard",
    subtitle: "Institutional Tactical Intelligence Platform",
    description: "A centralized school safety platform with role-based access, secure student registry, real-time SMS emergency alerts, and government-level oversight across multiple institutions.",
    long_description: "SchoolGuard is a multi-tenant school safety and management platform with three authority tiers: Government SuperAdmin (sees all schools), School Admin (isolated to their campus), and a forensic-level Student Registry mapping students to verified parent mobile numbers. The tactical SMS gateway supports pre-configured Red/Amber/Blue/Idle alert protocols. During peace, schools operate independently. During crisis, the government account can bypass local delays and broadcast master SMS alerts to all parents simultaneously.",
    features: [
      "Government SuperAdmin: global visibility + hot-swap into any school portal",
      "Campus isolation: School A cannot see School B's data",
      "Forensic student registry with dual parent mobile verification",
      "Tactical SMS gateway with Red/Amber/Blue/Idle alert protocols",
      "PWA-compliant for use on field devices during emergencies",
    ],
    challenges: [
      "Multi-tenant data isolation: enforcing school-level boundaries while the government tier sees everything",
      "Real-time SMS dispatch at scale without a dedicated telecom backend",
      "Designing alert templates that auto-inject student name and safe-zone location",
    ],
    tech_stack: ["React", "Tailwind CSS", "Recharts", "PWA", "SMS Gateway", "Multi-tenant Architecture"],
    live_url: "https://school-guard.vercel.app/", 
    github_url: "https://github.com/S1A8H3I4L/SchoolGuard",
  },
  // ── NOV–DEC 2025 ──
  {
    id: "9", slug: "vaultify", order: 9, accent: "yellow", featured: false,
    cover_emoji: "☁️", role: "Solo Developer", duration: "Self Learning · Nov–Dec 2025",
    name: "Vaultify",
    subtitle: "Secure Cloud Storage Platform",
    description: "A Google Drive–inspired secure cloud storage platform with Google OAuth, drag-and-drop uploads, user-isolated file management, and storage analytics.",
    long_description: "Vaultify is a full-featured cloud storage demo built in React 19 + TypeScript. It implements Google OAuth 2.0 for authentication (no passwords stored), per-user file isolation, drag-and-drop upload, a right-click context menu for rename/star/delete/share actions, Grid and List view toggle, a Trash system with restore and permanent delete, and a Recharts storage analytics panel breaking down usage by file type. An intelligent assistant layer provides context-aware file suggestions and natural-language search.",
    features: [
      "Google OAuth 2.0 — no passwords, per-user file isolation",
      "Drag-and-drop upload with right-click context menu (rename, star, delete, share)",
      "Grid / List view toggle with Trash system (restore + permanent delete)",
      "Storage analytics dashboard with Recharts file-type breakdown",
      "Context-aware AI file assistant with natural language search",
    ],
    challenges: [
      "Simulating user-isolated storage without a real cloud backend",
      "Building a right-click context menu that works reliably on both desktop and mobile",
      "Making the Recharts analytics feel live without real quota data",
    ],
    tech_stack: ["React", "TypeScript", "Tailwind CSS", "Google OAuth", "Recharts", "Lucide React", "Vite"],
    live_url: "https://vaultify-secure-cloud-storage.vercel.app/", 
    github_url: "https://github.com/S1A8H3I4L/Vaultify",
  },
  // ── JAN–DEC 2025 ──
  {
    id: "10", slug: "course-management-system", order: 10, accent: "teal", featured: false,
    cover_emoji: "🎓", role: "Full-Stack Developer", duration: "MCA Sem 2–3 · Jan–Dec 2025",
    name: "Course Management System",
    subtitle: "Academic Management Platform | MCA (Sem 2–3) · GLS University",
    description: "A full academic management system for GLS University covering course creation, syllabus versioning, batch progression, student lifecycle tracking, and MIS reports.",
    long_description: "Developed as the MCA Sem 2–3 mini project at GLS University (certified Nov 21, 2025). The system manages the complete academic lifecycle: departments → courses → syllabi (with effective year and tenure) → batches → semesters → subjects (core + elective tracks) → divisions → students. Student profiles include admission details, dropouts, and re-admission scenarios. MIS reports (matplotlib + seaborn) cover Course vs Syllabus Validity, Batch & Semester Progress, Student Lifecycle Distribution, Core vs Elective per Track, and Enrollment Growth. Sahil led backend, frontend, database design, and integration.",
    features: [
      "Course + syllabus versioning with effective year, tenure, and AWS S3 PDF upload",
      "Batch-wise semester progression with division management",
      "Student lifecycle: enrollment, dropout, and re-admission tracking",
      "Role-based access: Admin and Student portals",
      "MIS reports: 6 chart types (bar, line, pie, grouped bar) generated with matplotlib/seaborn",
    ],
    challenges: [
      "Modelling the many-to-many relationships between subjects, tracks, semesters, and batches in EF Core",
      "Syllabus versioning: linking a batch to a specific syllabus year without breaking historical data",
      "Generating consistent, publication-quality MIS charts without a BI tool",
    ],
    tech_stack: ["React", "TypeScript", ".NET 8 Minimal API", "PostgreSQL", "EF Core", "AWS S3", "JWT", "Python (matplotlib, seaborn)"],
    // live_url: "#", 
    // github_url: "https://github.com/S1A8H3I4L",
  },
  // ── OCT 2025 (Hackathon) ──
  {
    id: "11", slug: "expense-management", order: 11, accent: "pink", featured: false,
    cover_emoji: "🧾", role: "Full Stack Developer", duration: "Self Learning · Oct 2025",
    name: "Expense Management System",
    subtitle: "Role-Based Expense Platform",
    description: "A role-based expense management platform with automated multi-level approval workflows, OCR-based receipt scanning, and multi-currency expense handling.",
    long_description: "Built for this system automates the full reimbursement lifecycle. Employees submit expenses; OCR auto-fills Amount, Date, Description, and Merchant from receipt photos. The approval chain is fully configurable — sequential (Manager → Finance → Director), percentage-based, or CFO-bypass. Multi-currency support uses live exchange rates. The company currency is auto-set from the country selected at signup.",
    features: [
      "OCR receipt scanning: auto-extracts key fields from photos",
      "Configurable multi-level approvals: sequential, percentage, and hybrid rules",
      "Multi-currency with live exchange rate API (restcountries + exchangerate-api)",
      "Role-based portals: Employee / Manager / Admin",
      "Expense filter by status, category, and date with search",
    ],
    challenges: [
      "Conditional approval logic: combining sequential, percentage, and CFO-bypass in one engine",
      "Live currency conversion at submission vs. at approval date",
      "OCR accuracy on low-quality or handwritten receipts",
    ],
    tech_stack: ["React", "Vite", "Node.js", "Express", "SQL", "Tailwind CSS", "OCR", "REST APIs"],
    live_url: "https://expense-managements.vercel.app/", 
    github_url: "https://github.com/S1A8H3I4L/Expense-Management",
  },
  // ── OCT 2025 (SIH) ──
  {
    id: "12", slug: "qlickin", order: 12, accent: "blue", featured: true,
    cover_emoji: "📱", role: "Full Stack Developer", duration: "SIH 2025 · Oct 2025",
    name: "Qlickin",
    subtitle: "Automated Student Attendance System | Smart India Hackathon 2025",
    description: "An automated student attendance and analytics system with dynamic QR code + OTP + face recognition, real-time validation, and web/mobile dashboards — preventing proxy attendance.",
    long_description: "Built for Smart India Hackathon 2025 (Problem Statement SIH25016 — 'Automated Student Attendance Monitoring and Analytics System for Colleges', Theme: Smart Education). Qlickin uses time-bound QR codes (6-second refresh via Redis + TOTP) that are impossible to share as screenshots, combined with face recognition for a second anti-proxy layer. The architecture spans a React Native student app, React + Redux faculty and admin dashboards, a Node.js + Express microservices backend, MongoDB Atlas, Redis caching, Socket.io for real-time updates, OneSignal push notifications, and AWS deployment.",
    features: [
      "Dynamic QR codes refreshing every 6 seconds via Redis + TOTP — screenshot-proof",
      "Face recognition (OpenCV) as a second anti-proxy verification layer",
      "Real-time attendance sync via Socket.io with MongoDB Atlas",
      "Interactive analytics dashboards (Recharts/Chart.js) for faculty and admin",
      "OneSignal + Twilio push/SMS notifications to students and parents",
    ],
    challenges: [
      "QR refresh reliability when students have intermittent internet during class",
      "Face recognition latency: keeping inference fast enough for classroom-scale use",
      "Designing Firestore/MongoDB rules for multi-institution data isolation",
    ],
    tech_stack: ["React Native", "React", "Redux", "Node.js", "Express", "MongoDB", "Redis", "Socket.io", "OpenCV", "AWS", "Docker", "OneSignal", "Twilio"],
    live_url: "https://qlickin.vercel.app/", 
    github_url: "https://github.com/S1A8H3I4L/Qlickin",
  },
  // ── MAY–AUG 2025 ──
  {
    id: "13", slug: "foodzzz", order: 13, accent: "yellow", featured: false,
    cover_emoji: "🍔", role: "Solo Developer", duration: "Self Learning · May–Aug 2025",
    name: "FoodZzz",
    subtitle: "Smart Food Ordering Platform",
    description: "A full-stack smart food ordering platform with Google OAuth, dynamic cart, Google Pay integration, downloadable recipe PDFs, and a role-based admin dashboard.",
    long_description: "FoodZzz lets users log in with Google, browse Breakfast/Lunch/Dinner categories, manage a real-time cart, and pay via Google Pay. After payment, a downloadable recipe PDF is unlocked. A personal dashboard shows profile data and full order history. The superuser panel (restricted to sahilpanchal1818@gmail.com) shows all registered users with avatars, login/logout history, and a one-click delete action. Contact form submissions go directly to the admin email.",
    features: [
      "Google OAuth login with personalized dashboard (avatar, name, email, order history)",
      "Category browsing (Breakfast / Lunch / Dinner) with real-time cart updates",
      "Google Pay integration — PDF recipe download unlocked post-payment",
      "Superuser panel: view all users, login/logout history, and delete users",
      "Contact form with email notification to admin",
    ],
    challenges: [
      "Session-based cart keeping state consistent across multiple browser tabs",
      "Locking the recipe PDF download behind payment verification server-side",
      "Restricting the superuser panel to a specific email without a full RBAC system",
    ],
    tech_stack: ["Django", "TailwindCSS", "SQLite3", "Google OAuth", "Google Pay", "Python", "JavaScript"],
    // live_url: "#", 
    github_url: "https://github.com/S1A8H3I4L/FoodZzz",
  },
  // ── JULY 2025 (Hackathon) ──
  {
    id: "14", slug: "stackit", order: 14, accent: "teal", featured: false,
    cover_emoji: "📚", role: "Full Stack Developer", duration: "Odoo Hackathon · Jul 2025",
    name: "StackIt",
    subtitle: "Minimal Q&A Forum Platform | Odoo Hackathon",
    description: "A minimal Q&A forum enabling collaborative learning with role-based access, rich-text posting, voting, answer acceptance, and a real-time notification system.",
    long_description: "StackIt is a lightweight Stack Overflow–style Q&A forum built for the Odoo Hackathon. Guest users can read all content; registered users can ask questions (with tags), post richly formatted answers, upvote/downvote, and accept the best answer. Admins can moderate all content. A bell icon with unread count notifies users when their question receives an answer. The rich text editor supports bold/italic/strikethrough, numbered/bullet lists, emoji, hyperlinks, image uploads, and text alignment.",
    features: [
      "Guest / Registered / Admin role system with progressive permissions",
      "Rich text editor: formatting, lists, emoji, hyperlinks, image uploads",
      "Upvote/downvote system with answer acceptance by question author",
      "Bell notification with unread count and dropdown of recent alerts",
      "Tag-based question categorisation (e.g. React, JWT)",
    ],
    challenges: [
      "Rich text serialisation that round-trips correctly between editor and stored HTML",
      "Real-time notification count without polling — using event emitters server-side",
      "Preventing vote manipulation by the same user on their own content",
    ],
    tech_stack: ["React", "Node.js", "Express", "MySQL", "Rich Text Editor", "JWT", "REST API"],
    // live_url: "#", 
    github_url: "https://github.com/S1A8H3I4L/StackIt",
  },
  // ── SEP–NOV 2024 ──
  {
    id: "15", slug: "conversational-image-recognition-chatbot", order: 15, accent: "pink", featured: false,
    cover_emoji: "🤖", role: "AI/ML Developer", duration: "SIH 2024 · Sep–Nov 2024",
    name: "Image Recognition Chatbot",
    subtitle: "Conversational AI Vision System | SIH 2024",
    description: "Combines deep learning image recognition with NLP-driven, context-aware conversations for interactive, human-like AI communication.",
    long_description: "Built for SIH 2024, this system lets users upload or point a camera at any image and then have a natural conversation about what's in it. The deep learning backbone handles accurate object/scene recognition; an NLP layer (context-aware, multi-turn) maintains conversation history so follow-up questions ('What colour is it?' 'How many are there?') work naturally. The goal was AI that feels like a knowledgeable friend rather than a command-response bot.",
    features: [
      "Deep learning image recognition with high object/scene classification accuracy",
      "Multi-turn NLP conversations with context carry-over across questions",
      "Human-like response generation without rigid template matching",
      "Real-time inference on uploaded images and camera feed",
      "Built for SIH 2024 — Theme: Smart Education",
    ],
    challenges: [
      "Keeping NLP context consistent across multi-turn conversations without a large memory footprint",
      "Inference latency on real-time camera feed vs. batch uploaded images",
      "Bridging the vision model output vocabulary to natural language descriptions",
    ],
    tech_stack: ["Python", "TensorFlow", "NLP", "Deep Learning", "OpenCV", "Flask", "React"],
    // live_url: "#", 
    // github_url: "https://github.com/S1A8H3I4L",
  },
  // ── JUN 2023–MAY 2024 ──
  {
    id: "16", slug: "hap-heart-attack-prediction", order: 16, accent: "blue", featured: false,
    cover_emoji: "❤️", role: "ML Developer", duration: "BCA Sem 5–6 · Jun 2023–May 2024",
    name: "HAP: Heart Attack Prediction",
    subtitle: "ML Health Risk Prediction | BCA (Sem 5–6)",
    description: "An SVM-based heart attack risk prediction system with health data preprocessing, model training, and a user-friendly web interface with preventive guidance for at-risk users.",
    long_description: "HAP (Heart Attack Prediction) was the BCA final-year project. It collects patient health metrics (age, cholesterol, blood pressure, etc.), preprocesses and normalises the data, trains an SVM classifier, and serves predictions through a clean web interface. At-risk users see personalised preventive guidance. The project prioritises ethical testing and data privacy — no personally identifiable information is stored post-prediction.",
    features: [
      "SVM model trained on health metrics with preprocessing and feature normalisation",
      "Web-based risk prediction interface with real-time results",
      "Personalised preventive guidance for at-risk users",
      "Data privacy: no PII stored post-prediction",
      "Ethical testing with transparent model accuracy reporting",
    ],
    challenges: [
      "Class imbalance in the health dataset requiring SMOTE oversampling",
      "Communicating probabilistic risk in plain language without being alarmist",
      "Building a model explainability layer so users understand why they're at risk",
    ],
    tech_stack: ["Python", "Scikit-learn", "SVM", "Pandas", "NumPy", "Flask", "HTML", "CSS"],
    // live_url: "#", 
    github_url: "https://github.com/S1A8H3I4L/HAP---Heart-Attack-Prediction",
  },
];

export const fallbackSkills: Skill[] = [
  { id: "1", order: 1, color: "yellow", category: "Frontend", items: ["React.js", "HTML5", "CSS3", "JavaScript", "TypeScript", "Tailwind CSS", "Bootstrap", "Material UI", "ShadCN"] },
  { id: "2", order: 2, color: "teal",   category: "Backend",  items: ["Django", "Flask", "ASP.NET Core (.NET)", "Node.js", "Express.js"] },
  { id: "3", order: 3, color: "pink",   category: "AI / ML",  items: ["Python", "TensorFlow", "Scikit-learn", "SVM", "NLP", "CNN", "OpenCV", "Machine Learning"] },
  { id: "4", order: 4, color: "blue",   category: "Database", items: ["MySQL", "PostgreSQL", "MongoDB", "SQLite", "Firebase Firestore"] },
  { id: "5", order: 5, color: "white",  category: "Tools & DevOps", items: ["Git", "GitHub", "Docker (Basics)", "Linux", "CI/CD", "Postman", "Figma", "AWS S3"] },
  { id: "6", order: 6, color: "black",  category: "Concepts", items: ["DSA", "OOP", "System Design", "REST APIs", "JWT", "OAuth", "RBAC", "Event-Driven Arch"] },
];

export const fallbackExperience: Experience[] = [
  {
    id: "1", order: 1, badge_color: "yellow",
    title: "Software Engineer Intern (Full Stack Developer)",
    company: "Zentrixa Solutions",
    type: "Internship",
    period: "Nov 2025 – Apr 2026",
    bullets: [
      "Engineered full-stack applications and integrated RESTful APIs across core workflows during a 6-month internship, improving backend scalability and application performance by 20%.",
      "Implemented secure JWT and OAuth authentication mechanisms across 5+ backend modules, reducing unauthorized access vulnerability risks.",
      "Optimized PostgreSQL database queries and indexing structures to improve overall backend reliability and data retrieval speed.",
    ],
  },
  {
    id: "2", order: 2, badge_color: "teal",
    title: "Python / Backend Developer Intern",
    company: "Proglan FutureTech Pvt. Ltd.",
    type: "Internship",
    period: "Jun 2023 – May 2024",
    bullets: [
      "Engineered and scaled 15+ REST API endpoints using Python, implementing robust JWT and OAuth authentication protocols to ensure secure enterprise data transmission.",
      "Executed complex database query optimizations and indexing strategies, cutting server response latency for core backend data retrieval operations.",
      "Collaborated within cross-functional engineering squads to design modular backend services, standardizing API documentation and improving system reliability.",
    ],
  },
];

export const fallbackCertifications: Certification[] = [
  
  {
    id: "1",
    icon: "🧠",
    name: "Claude Platform 101",
    issuer: "Anthropic · Jun 2026",
    year: "2026",
  },
  {
    id: "2",
    icon: "✨",
    name: "Claude 101",
    issuer: "Anthropic · Jun 2026",
    year: "2026",
  },
  {
    id: "3",
    icon: "📊",
    name: "Data Analytics Job Simulation",
    issuer: "Deloitte Australia × Forage · Jul 2025",
    year: "2025",
  },
  { id: "4", icon: "🎓", name: "Course Management System (MCA Mini Project)", issuer: "GLS University · FCAIT · Nov 2025", year: "2025" },
  { id: "5", icon: "🎓", name: "Bachelor of Computer Applications", issuer: "GLS University · CGPA: 8.80", year: "2024" },
  {
    id: "6",
    icon: "🤖",
    name: "Career Essentials in Generative AI",
    issuer: "Microsoft × LinkedIn Learning · Jul 2024",
    year: "2024",
  },
  
];

export const fallbackEducation: Education[] = [
  {
    id: "1", order: 1, status: "COMPLETED",
    degree: "Master of Computer Applications (MCA)",
    college: "GLS University · FCAIT",
    location: "Ahmedabad, Gujarat",
    period: "Aug 2024 – Apr 2026",
    gpa_or_percent: "CGPA: 9.47",
  },
  {
    id: "2", order: 2, status: "COMPLETED",
    degree: "Bachelor of Computer Applications (BCA)",
    college: "GLS University",
    location: "Ahmedabad, Gujarat",
    period: "Aug 2021 – May 2024",
    gpa_or_percent: "CGPA: 8.80",
  },
  {
    id: "3", order: 3, status: "COMPLETED",
    degree: "H.S.C. (GSEB)",
    college: "The H.B. Kapadia New High School",
    location: "Gujarat Board",
    period: "2021",
    gpa_or_percent: "Percentage: 66.93%",
  },
  {
    id: "4", order: 4, status: "COMPLETED",
    degree: "S.S.C. (GSEB)",
    college: "The H.B. Kapadia New High School",
    location: "Gujarat Board",
    period: "2019",
    gpa_or_percent: "Percentage: 65.50%",
  },
];
